services:
  # Local MQTT Broker
  mqtt_local_broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt_local_broker
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqtt_local_data:/mosquitto/data
      - mqtt_local_logs:/mosquitto/log
    restart: unless-stopped
    networks:
      - mqtt_network

  # Cloud MQTT Broker (simulated)
  mqtt_cloud_broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt_cloud_broker
    ports:
      - "1884:1884"
    volumes:
      - ./config/cloud_mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqtt_cloud_data:/mosquitto/data
      - mqtt_cloud_logs:/mosquitto/log
    restart: unless-stopped
    networks:
      - mqtt_network

  # PLC 1 - Manufacturing Line
  plc1:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: plc1
    volumes:
      - ./plc1.py:/app/main.py
    depends_on:
      - mqtt_local_broker
    environment:
      - BROKER=mqtt_local_broker
      - PORT=1883
    restart: unless-stopped
    networks:
      - mqtt_network

  # PLC 2 - Energy Management
  plc2:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: plc2
    volumes:
      - ./plc2.py:/app/main.py
    depends_on:
      - mqtt_local_broker
    environment:
      - BROKER=mqtt_local_broker
      - PORT=1883
    restart: unless-stopped
    networks:
      - mqtt_network

  # PLC 3 - Environmental Monitoring
  plc3:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: plc3
    volumes:
      - ./plc3.py:/app/main.py
    depends_on:
      - mqtt_local_broker
    environment:
      - BROKER=mqtt_local_broker
      - PORT=1883
    restart: unless-stopped
    networks:
      - mqtt_network

  # HMI 1 - Manufacturing Dashboard
  hmi1:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: hmi1
    volumes:
      - ./hmi1.py:/app/main.py
    depends_on:
      - mqtt_local_broker
      - plc1
    environment:
      - BROKER=mqtt_local_broker
      - PORT=1883
    restart: unless-stopped
    networks:
      - mqtt_network
    tty: true
    stdin_open: true

  # HMI 2 - Energy Dashboard
  hmi2:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: hmi2
    volumes:
      - ./hmi2.py:/app/main.py
    depends_on:
      - mqtt_local_broker
      - plc2
    environment:
      - BROKER=mqtt_local_broker
      - PORT=1883
    restart: unless-stopped
    networks:
      - mqtt_network
    tty: true
    stdin_open: true

  # Historian Database
  historian:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: historian
    volumes:
      - ./historian.py:/app/main.py
      - historian_data:/app/data
    depends_on:
      - mqtt_local_broker
      - plc1
      - plc2
      - plc3
    environment:
      - BROKER=mqtt_local_broker
      - PORT=1883
      - DB_FILE=/app/data/historian.db
    restart: unless-stopped
    networks:
      - mqtt_network

  # Bridge Client
  bridge:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: bridge
    volumes:
      - ./bridge.py:/app/main.py
    depends_on:
      - mqtt_local_broker
      - mqtt_cloud_broker
      - plc2
      - plc3
    environment:
      - LOCAL_BROKER=mqtt_local_broker
      - LOCAL_PORT=1883
      - CLOUD_BROKER=mqtt_cloud_broker
      - CLOUD_PORT=1884
    restart: unless-stopped
    networks:
      - mqtt_network

  # Cloud Dashboard
  cloud_dashboard:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: cloud_dashboard
    volumes:
      - ./cloud_dashboard.py:/app/main.py
    depends_on:
      - mqtt_cloud_broker
      - bridge
    environment:
      - BROKER=mqtt_cloud_broker
      - PORT=1884
    restart: unless-stopped
    networks:
      - mqtt_network
    tty: true
    stdin_open: true

  # Analytics Engine
  analytics:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: analytics
    volumes:
      - ./analytics.py:/app/main.py
      - analytics_data:/app/data
    depends_on:
      - mqtt_cloud_broker
      - bridge
    environment:
      - BROKER=mqtt_cloud_broker
      - PORT=1884
      - DB_FILE=/app/data/analytics.db
    restart: unless-stopped
    networks:
      - mqtt_network

  # Enhanced Logger (existing)
  logger:
    build:
      context: ./logger
      dockerfile: Dockerfile
    container_name: logger
    depends_on:
      - mqtt_local_broker
    environment:
      - BROKER=mqtt_local_broker
      - PORT=1883
    restart: unless-stopped
    networks:
      - mqtt_network

networks:
  mqtt_network:
    driver: bridge

volumes:
  mqtt_local_data:
  mqtt_local_logs:
  mqtt_cloud_data:
  mqtt_cloud_logs:
  historian_data:
  analytics_data:
